### PR TITLE
Fix errors in monitor start/stop code.

### PR DESCRIPTION
**Pull request by jcalcote**
Hi Yaguang - This change set fixes two issues in start/stop monitor code. First, there was a bug in the changes to driver.py's _operate_ceph_daemon that i made a while back (my fault) - I tried to pass an integer (id) as a string to "replace". This was throwing, but the exception was caught at a higher layer and simply flagged as a monitor start/stop failure. Second, start_monitor and stop_monitor were written to access ceph.conf for information on individual monitors, but now that we no longer require [mon.X] sections in the ceph.conf file, this code had to be rewritten. I added a routine _get_ceph_mon_map, that uses "ceph mon dump -f json" to acquire monitor configuration information. Finally, in stop_server, if there were no osd's on the target host, then no attempt was made to top the monitor.

### CODE REVIEW

**Comment by lihaijing** [comment]
This fix doesn't work well when the ceph cluster is deployed by ceph-deploy and then imported into vsm. Ceph-deploy uses hostname as monitor's id by default, not a number id.

**Comment by jcalcote** [comment]
Hi @lihaijing - do you have any suggestions on how I might fix it in a manner that would work for both scenarios? As it turns out, our use case is also import cluster created by ceph-deploy, so we care about all the possible variations in ceph-deploy clusters. We're on fairly late ceph code, so perhaps they've changed ceph-deploy recently to work with ids?

Thanks,
John

**Comment by lihaijing** [comment]
@jcalcote  Hi, I think in the output of "ceph mon dump -f json", the "name" is actual mon id not "rank". So I modify my codes like this and I'm not sure about whether commit these changes:
code

**Comment by jcalcote** [comment]
@lihaijing - you are absolutely correctly. This was my mistake. Please commit your changes and we'll look for issues in start/stop mon that may (or may not) come up from these changes and fix them as we find them. How could I have missed this? Of course, rank is not mon id. I must have been initially confused by the way the code was written to work with numbers and found rank to be the only number on the monitor dump output. I had added code to operate_ceph_daemon that tried to convert that number to a host name. Not needed. Please do commit.

**Comment by lihaijing** [comment]
@jcalcote Hi, I've already commited my codes in pull request #511 .

**Pull request merged**
