### PR TITLE
Change import_cluster to obtain osd config from ceph cluster instead of ceph.conf

### PR DESCRIPTION
**Pull request by jcalcote**
Hi Yaguang, This is work that really should have been done before 2.1 shipped, but we didn't realized it was broken until after it shipped. This change allows import_cluster to work against ceph.conf files that do not have osd.x sections. Instead of reading osd configuration from ceph.conf, it queries ceph and ceph-disk to determine osd configuration and local drive mapping data.

Note that we had to make a change to rootwrap configuration - it was set up to find ceph-disk in /usr/bin, but it's actually found in /usr/sbin. This is apparently the first time ceph-disk has been needed by vsm so this error was never caught originally.

### CODE REVIEW

**Comment by ywang19** [comment]
the ceph-disk output is different on firefly, here is what I see from ceph-disk on firefly:
ubuntu@node1:~$ sudo ceph-disk list
/dev/sda :
 /dev/sda1 other, ext4, mounted on /
 /dev/sda2 other, 0x5
 /dev/sda5 swap, swap
/dev/sdb :
 /dev/sdb1 other, 0fc63daf-8483-4772-8e79-3d69d8477de4
 /dev/sdb2 other, 0fc63daf-8483-4772-8e79-3d69d8477de4
 /dev/sdb3 other, 0fc63daf-8483-4772-8e79-3d69d8477de4
 /dev/sdb4 other, xfs, mounted on /var/lib/ceph/osd/osd0
 /dev/sdb5 other, xfs, mounted on /var/lib/ceph/osd/osd1
 /dev/sdb6 other, xfs, mounted on /var/lib/ceph/osd/osd2
/dev/sr0 other, unknown
/dev/sr1 other, unknown
ubuntu@node1:~$ ceph -v
ceph version 0.80.11 (8424145d49264624a3b0a204aedb127835161070)

**Comment by jcalcote** [comment]
Ok. I'll see if I can come up with a more universal solution.

John

**Comment by jcalcote** [comment]
With this second change set to this dev branch, I've added support for both firefly and infernalis. Firefly requires a bit more work to get the same information, but it's available via the ceph daemon command.

**Comment by jcalcote** [comment]
Closing this request. Will reopen after rebase.

**Pull request closed without merging**
