### PR TITLE
VSM-53: initial support for integration of existing clusters not basing on ceph.conf

### PR DESCRIPTION
**Pull request by rzarzynski**
This is PR is a part of wider efforts to bring support for integration of already existing Ceph clusters into VSM. The code provides ability  to grab information about a cluster without referring to its _ceph.conf_ and thus allows work with deployments realized through _ceph-deploy_ utility.

We still need:
* acquire information about CRUSH hierarchy and prepare appropriate structure of nested zones;
* map rulesets info storage groups.

### CODE REVIEW

**Comment by ywang19** [comment]
Hi radoslow, considering potential implications, could you pull them to wip-53 branch?

**Comment by rzarzynski** [comment]
Hello Yaguang,

I initially tried to make this against _wip-53_ but there was some problems releated with DB structure. They seem to be fixed in _master_, so I rebased to it.

If you don't mind, I will send _wip-existing_cluster_support_ against _wip-53_ as it currently is - without changing parent of the first commit, so a lot other commits will be taken as well.

**Comment by ywang19** [comment]
That’s fine for wip-53. I could merge them into wip-53 initially, then further refine them.

**Comment by ywang19** [comment]
Hi Radoslow, I directly merged them into wip-53 branch.

**Pull request closed without merging**
