### PR TITLE
Add changes for vsm dashboard configuration when support remote db

### PR DESCRIPTION
**Pull request by zhangjun-inspur**
When vsm support remote database, both vsm and vsm-dashboard should be configured correctly. Or else, the web page may not work well on the vsm dashboard.
The code commited is only a temporary solution, the current version is to config vsm and dashboard twice when use remote db, one is for local db in process "setup_vsm " and "setup_vsmdash" (/usr/local/bin/vsm-installer) in which the commands for config will eventually fail, and the other one is for remote db which will success.
It's best to re-write the function setup_vsm and setup_vsmdash for vsm installation in the future version.

### CODE REVIEW

**Comment by ywang19** [comment]
actually, the database in vsm-dashboard doesn't take in effect, so should not break web pages.

**Comment by zhangjun-inspur** [comment]
Hi, @ywang19, you're right, I re-deployed the vsm, and found no mistakes on the web pages, it's my mistake. Does it mean that dashboard db or dashboard user will not be created in local or remote database any more?

**Comment by flyingfish007** [comment]
@zhangjun-inspur 
User is stored in the keystone db.
The vsm project uses the "vsm" db.
The "dashboard" db is only for django.

**Comment by zhangjun-inspur** [comment]
Hi, @flyingfish007, thanks for your answering. I still have two questions. 
1, If I use remote database, the dashboard db and dashboard user will not be used?
2, If I use local database (on vsm controller), the dashboard db and dashboard user will be used?

**Comment by flyingfish007** [comment]
Whether you use local or remote db, the dashboard db and dashboard user are useless(you can annotate them, maybe they will be removed later).
As you see, the install.sh(function _config_db_controler) will create vsm user on the remove mysql. So you can use the vsm user(or other user you create) and password to login.
In the local_settings file, the parameter "OPENSTACK_HOST" and "OPENSTACK_KEYSTONE_URL" are useful.

**Pull request closed without merging**
